name: CI/CD - Rendez-vous Médicaux

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # ==============================
  # CI : CONTINUOUS INTEGRATION
  # ==============================
  ci:
    name: CI - Build and Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout du code
        uses: actions/checkout@v5

      - name: Configuration de Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Exécuter les tests
        run: mvn clean test

      - name: Compiler et créer le JAR
        run: mvn package -DskipTests

      - name: Upload du JAR
        uses: actions/upload-artifact@v6
        with:
          name: application-jar
          path: target/*.jar


  # ==============================
  # CD : CONTINUOUS DELIVERY
  # ==============================
  cd:
    name: CD - Delivery
    needs: ci
    runs-on: ubuntu-latest

    # Le CD est exécuté seulement après
    # la réussite complète du CI
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:

      - name: Télécharger le JAR créé par CI
        uses: actions/download-artifact@v7
        with:
          name: application-jar
          path: deployment

      - name: Vérifier le livrable
        run: |
          echo "Application validée par le pipeline CI"
          echo "Livrable prêt pour le déploiement"
          ls -R deployment

      - name: Préparer la livraison
        run: |
          echo "Continuous Delivery terminée avec succès"
          echo "Le fichier JAR est prêt à être déployé"