name: CI/CD - Rendez-vous Médicaux

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Installer Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Tester
        run: mvn clean test

      - name: Construire le JAR
        run: mvn package -DskipTests

      - name: Sauvegarder l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
